version: '3.8'

#lancer le serveur web dagster
services:
  dagster:
    build: .
    container_name: dagster_app
    volumes:
      - .:/opt/dagster/app
      - ./data:/opt/dagster/app/data
    ports:
      - "3000:3000"
      - "8081:8081"
    environment:
      - DAGSTER_HOME=/opt/dagster/app
    restart: always

  #le daemon indispensable pour lancer les taches
  dagster_daemon:
    build: .
    container_name: dagster_daemon
    # On lui dit de lancer le daemon
    command: dagster-daemon run
    volumes:
      - .:/opt/dagster/app
      - ./data:/opt/dagster/app/data
    environment:
      - DAGSTER_HOME=/opt/dagster/app/data/dagster_home
    restart: always

  dbt:
    build: .
    container_name: dbt_service
    volumes:
      - .:/opt/dagster/app
      - ./data:/opt/dagster/app/data
    environment:
      - DBT_PROFILES_DIR=/opt/dagster/app/dbt_project
    working_dir: /opt/dagster/app/dbt_project

  dashboard:
    build: .
    container_name: streamlit_app
    volumes:
      - .:/opt/dagster/app
      - ./data:/opt/dagster/app/data
    ports:
      - "8501:8501"
    working_dir: /opt/dagster/app
    command: streamlit run app.py
    restart: always
