version: '3.8'

services:
  dagster:
    build: .
    container_name: dagster_app
    volumes:
      - .:/opt/dagster/app
      - ./data:/opt/dagster/app/data
    ports:
      - "3000:3000"
    environment:
      - DAGSTER_HOME=/opt/dagster/app
    restart: always
